### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by Fabus1184** [svenstaro/bvh#102]
There are a lot of changes in the repository, but the last release is from 8 months ago. Can the current state be released as 0.7.3?

**Comment by svenstaro** [comment]
@marstaik What do you think?

**Comment by svenstaro** [comment]
@Fabus1184 Would you have some time and interest to help with the maintenance of this library? I don't have so much time for this myself currently.

**Comment by Fabus1184** [comment]
> @Fabus1184 Would you have some time and interest to help with the maintenance of this library? I don't have so much time for this myself currently.

I'll see what I can do, but I can't promise anything nor am I an expert on BVHs 😅

**Comment by svenstaro** [comment]
For starters, would you like to prepare the release by writing some release notes? There's a `CHANGELOG.md` but I don't think it has all the changes. After you make a PR for that, I can cut a release.

**Comment by Fabus1184** [comment]
There's not that much missing from the changelog, but here's my first take https://github.com/Fabus1184/bvh/blob/master/CHANGELOG.md.

Also, there are quite big changes, so maybe the new release should be a new minor version 🤷

**Comment by svenstaro** [comment]
Ideally I'd like #99 to get in before we do a release.
