### ISSUE TITLE
FlatNode's fields should be public.

### ISSUE THREAD

**Issue by omni-viral** [svenstaro/bvh#33]
Due to private fields and no access methods `FlatNode` cannot be used on GPU.

**Comment by svenstaro** [comment]
True, would accept a quick PR for this.

**Comment by omni-viral** [comment]
Also `AABB` type is not compatible with structure I can define in shader due to alignment.
It would be great to just `memcpy` data into GPU buffer, but would require `#[repr(align(16))]` for `AABB` type.

**Comment by omni-viral** [comment]
I guess I would have to use custom flat node type since I need repr(C) and alignment :)
