### ISSUE TITLE
Support glam instead of or in addition to nalgebra?

### ISSUE THREAD

**Issue by hrydgard** [svenstaro/bvh#38]
glam (https://github.com/bitshifter/glam-rs) is a much slimmer, faster-to-build and neater vector math library than nalgebra, which is so complex that it often triggers Rust compiler bugs (a discussion to be had elsewhere).

It might be possible to support both through feature flags and some type redefinitions.

**Comment by svenstaro** [comment]
Yes, I've seen this library recently and it seems pretty great. Should be somewhat easy to port. I'd like to support both, if possible. However, it's quite likely that I won't have the time to do this soon. Would you like to take a stab at this?

**Comment by hrydgard** [comment]
Yeah I just might. Though it might be harder than I first thought to support both simultaneously, maybe it'll just have to be a fork of this library, we'll see.
