### ISSUE TITLE
BVHNode is Debug, but BVH itself is not

### ISSUE THREAD

**Issue by curldivergence** [svenstaro/bvh#81]
Hi, I'm curious - why isn't the `Debug` trait derived for the `BVH` struct? It contains only one member - a vector of `BVHNode`'s which are `Debug` themselves, so could we make `BVH` `Debug`, too, or there is some reasoning against doing that? :) Thanks!

**Comment by svenstaro** [comment]
Dunno, try making it `Debug` and see if it's happy and then make an PR. :)

**Comment by curldivergence** [comment]
Done, thank you!

**Comment by svenstaro** [comment]
Closed via #82.
